### ISSUE TITLE
openjdk-openj9 builds on download page are randomly jdk or jre

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-website#381] opened 2018-12-19 12:06 UTC
The download page for the latest openjdk9-openj9 builds (https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=openj9) shows the following

Linux x64 | .tar.gz (86 MB) | Checksum
Linux x64 Large Heap | .tar.gz (47 MB) | Checksum
Windows x32 | .zip (43 MB) | Checksum
Windows x64 | .zip (43 MB) | Checksum
Linux s390x | .tar.gz (86 MB) | Checksum
Linux ppc64le | .tar.gz (46 MB) | Checksum
AIX ppc64 | .tar.gz (83 MB) | Checksum

The links to the smaller files point at the jre, the links to the larger files point at the jdk.

Not sure what the intent is (to point to one or the other or both), but pointing randomly at one or the other is not correct.  (Both would appear to be ideal otherwise it would not be easy for a user to find the 'missing' build (jdk or jre) for the release.)

**Comment by karianna** [comment] 2018-12-19 12:58
suspect this is a duplicate of the API bug

**Closed** 2019-01-09 16:53 UTC
Labels: bug
