### ISSUE TITLE
Add the OpenJ9 p & z Large Heap packages to the website

### ISSUE THREAD

**Issue by DanHeidinga** [AdoptOpenJDK/openjdk-website#627] opened 2019-12-03 13:54 UTC
Now that Adopt is building the large heap p & z packages [1] (and a big thanks for that!), can we get them added to the website as well?

We've previously exposed the large heap packages for Linux, Windows and Mac.

[1] https://github.com/AdoptOpenJDK/openjdk-build/issues/1400

**Comment by sxa555** [comment] 2019-12-03 14:20
I'd add aarch64 to that list as well, since the non-Large Heap OpenJ9 nightly builds don't build just now ... Unless you have a reason not to want to in development aarch64 builds published to the nightly stream?

**Comment by DanHeidinga** [comment] 2019-12-03 14:28
> Unless you have a reason not to want to in development aarch64 builds published to the nightly stream?

@0xdaryl can you comment on whether the aarch64 builds should be on the Adopt nightly page?  You have a better view of the state of those builds.

**Comment by karianna** [comment] 2019-12-06 14:44
This may be an API issue - when we swap over to v3 it'll be interesting to see if these just pop up.

**Comment by zl-wang** [comment] 2019-12-10 20:46
where are we with this (ppc64le large heap build)?  there are people waiting for it to pop up on the website.

**Comment by smlambert** [comment] 2019-12-10 23:09
We need someone to create a PR and welcome all contributors to help.

While waiting for some one to volunteer to do this work, if you need to pick up nightly builds, you can also get them directly from Jenkins jobs, or the releases repo (from where we pull them to serve them up on the website (via the API).

From Jenkins, see the "Last successful artifacts" from:
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-ppc64le-openj9-linuxXL/
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-s390x-openj9-linuxXL/
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9-linuxXL/

**Comment by karianna** [comment] 2020-01-08 07:41
@johnoliver - Whilst I'm passing through here - is the v3 API picking these up?

**Comment by sxa555** [comment] 2020-01-08 20:08
Looks like it might be on the basis that this link appears to download something :-)

https://api.adoptopenjdk.net/v3/binary/latest/11/ea/linux/aarch64/jdk/openj9/large/adoptopenjdk?project=jdk

So we can probably close this once the website is migrated to use the V3 API

**Comment by 0xdaryl** [comment] 2020-01-22 20:12
I can confirm that the AArch64 OpenJ9 build is downloadable from the link above, but it does not show up on the Nightly build page here (https://adoptopenjdk.net/nightly.html) when searching for OpenJ9 JDK11 builds.

I'm happy to open a PR to enable that (and might as well do P and Z Large Heap while I'm at it).  I just need someone to point me to where I need to make those modifications to have them appear in the nightly build.  Any guidance @gdams @sxa555 ?

[ I just noticed that @gdams self-assigned this a few days ago.  Not sure if this means a PR is imminent?  If not, if you point me in the right direction I can work on a PR hopefully by the end of the week. ]

**Comment by sxa555** [comment] 2020-01-23 00:01
@gdams told me in the last TSC call that it'd be a five minute job that he'd do for me as soonas we GA'd so we need to kick him again it seems ...

**Comment by smlambert** [comment] 2020-01-23 00:29
Fist to sky, @gdams API v3!!!!

**Comment by 0xdaryl** [comment] 2020-01-23 13:43
Great, thanks!  Much appreciated.

**Comment by sxa555** [comment] 2020-01-24 16:58
Fixed under https://github.com/AdoptOpenJDK/openjdk-website/pull/668

**Closed by sxa555** 2020-01-24 16:58 UTC
Labels: enhancement, good first issue, help wanted

**Comment by DanHeidinga** [comment] 2020-01-24 17:56
A big thank you to @gdams for delivering #668 and to everyone else involved in making this happen from the OpenJ9 community!
