### ISSUE TITLE
Suggestion: Add release feeds

### ISSUE THREAD

**Issue by redranamber** [AdoptOpenJDK/openjdk-website#350] opened 2018-11-03 05:59 UTC
It would make it easier to keep updated if your site had rss or atom feeds for each version's releases.

**Comment by supahgreg** [comment] 2018-11-06 00:18
Looks like GitHub already provides that, although there's some noise from the nightlies.  For example:
* https://github.com/AdoptOpenJDK/openjdk8-binaries/releases.atom
* https://github.com/AdoptOpenJDK/openjdk8-binaries/tags.atom
* https://github.com/AdoptOpenJDK/openjdk8-binaries/commits/master.atom

**Comment by breun** [comment] 2019-07-14 00:41
I think this issue is a duplicate of https://github.com/AdoptOpenJDK/TSC/issues/33

**Closed** 2023-01-23 15:23 UTC
Labels: enhancement, help wanted, good first issue - candidate
