### ISSUE TITLE
FAQ: Latest bottom href link is broken

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-website#654] opened 2020-01-13 17:23 UTC
Latest bottom href link is broken
>from them please raise an issue in the here

Another link with anchor seems good : 
`<a href="https://github.com/AdoptOpenJDK/openjdk-build/issues/1107#issuecomment-509272743"> this issue</a>`

you can try without "/" before #

https://github.com/AdoptOpenJDK/TSC#tsc-members

_Originally posted by @douph1 in https://github.com/AdoptOpenJDK/openjdk-website/issues/650#issuecomment-573723884_

**Comment by sxa555** [comment] 2020-01-13 17:25
Not sure what's going on here - I couldn't reproduce it in either Chrome 67 or Firefox 60.3.0esr and first and now I can ... Likewise for a colleague testing on Safari. It seems to go to the right place and then jump away. This will have to be investigated separately from the other FAQ updates I feel ... Suggestions welcome ;-)

**Comment by hendrikebbers** [comment] 2020-10-19 09:19
@sxa this looks like a Safari issue. Nothing that we can fix from my point of view. On my machine it works with Chrome but fails with Safari, too.

**Comment by karianna** [comment] 2022-02-14 13:01
Should be fixed at Adoptium.net

**Closed by karianna** 2022-02-14 13:01 UTC
Labels: bug, good first issue - candidate
