### ISSUE TITLE
x86 linux builds?

### ISSUE THREAD

**Issue by alexkoster** [AdoptOpenJDK/openjdk-website#602] opened 2019-11-05 20:55 UTC
* **Browser**:

Great effort and project!  Is it possible to add x86/i386/i486/i586/i686/32-bit/ia32 32-bit x86 Linux builds?

**Comment by karianna** [comment] 2019-11-05 22:33
Duplicate of the request in the openjdk-build repo.  FYI - We've not found volunteers to work on this yet.

**Closed by karianna** 2019-11-05 22:33 UTC
Labels: duplicate

**Comment by alexkoster** [comment] 2019-11-06 14:17
Thanks @karianna I now see multiple issues and will follow and comment on the https://github.com/ojdkbuild/ojdkbuild repository.  My apologies for posting in the wrong repo.

**Comment by karianna** [comment] 2019-11-06 15:33
@alexkoster that should be github.com/adoptopenjdk/openjdk-build for our binaries
